@Restaurants.API_HostAddress = https://localhost:7285

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy Delights 10",
  "Description": "A culinary experience line no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "123-456-7890",
  "City":"Metropolis",
  "Street":"123 Main St",
  "PostalCode" : "12-345"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

```

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
    "Id": 3,
    "Name": "Spicy Delights improved",
    "Description": "A culinary experience line no other",
    "Category": "Macedonian",
    "HasDelivery": true,
    "ContactEmail": "darkogele@hotmail.com"
}